#
# Copyright 2016 Quantopian, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# flake8: noqa

__version__ = "0.6.0"
from .stats import (
    aggregate_returns,
    alpha,
    alpha_aligned,
    alpha_beta,
    alpha_beta_aligned,
    annual_return,
    annual_volatility,
    beta,
    beta_aligned,
    cagr,
    beta_fragility_heuristic,
    beta_fragility_heuristic_aligned,
    gpd_risk_estimates,
    gpd_risk_estimates_aligned,
    calmar_ratio,
    capture,
    conditional_value_at_risk,
    cum_returns,
    cum_returns_final,
    down_alpha_beta,
    down_capture,
    downside_risk,
    excess_sharpe,
    max_drawdown,
    omega_ratio,
    roll_alpha,
    roll_alpha_aligned,
    roll_alpha_beta,
    roll_alpha_beta,
    roll_alpha_beta_aligned,
    roll_annual_volatility,
    roll_beta,
    roll_beta_aligned,
    roll_down_capture,
    roll_max_drawdown,
    roll_sharpe_ratio,
    roll_sortino_ratio,
    roll_up_capture,
    roll_up_down_capture,
    sharpe_ratio,
    simple_returns,
    sortino_ratio,
    stability_of_timeseries,
    tail_ratio,
    up_alpha_beta,
    up_capture,
    up_down_capture,
    value_at_risk,
    information_ratio,
    get_max_drawdown_period,
    tracking_error,
    roll_tracking_error,
    treynor_ratio,
    roll_treynor_ratio,
    m_squared,
    roll_m_squared,
    annual_active_risk,
    roll_annual_active_risk,
    annual_active_return,
    roll_annual_active_return,
    tracking_difference,
    annual_return_by_year,
    sharpe_ratio_by_year,
    information_ratio_by_year,
    annual_volatility_by_year,
    max_drawdown_by_year,
    max_drawdown_days,
    max_drawdown_weeks,
    max_drawdown_months,
    max_drawdown_recovery_days,
    max_drawdown_recovery_weeks,
    max_drawdown_recovery_months,
    second_max_drawdown,
    third_max_drawdown,
    second_max_drawdown_days,
    second_max_drawdown_recovery_days,
    third_max_drawdown_days,
    third_max_drawdown_recovery_days,
    win_rate,
    loss_rate,
    max_consecutive_up_days,
    max_consecutive_down_days,
    max_consecutive_up_weeks,
    max_consecutive_down_weeks,
    max_consecutive_up_months,
    max_consecutive_down_months,
    max_consecutive_gain,
    max_consecutive_loss,
    max_single_day_gain,
    max_single_day_loss,
    max_consecutive_up_start_date,
    max_consecutive_up_end_date,
    max_consecutive_down_start_date,
    max_consecutive_down_end_date,
    max_single_day_gain_date,
    max_single_day_loss_date,
    skewness,
    kurtosis,
    hurst_exponent,
    stock_market_correlation,
    bond_market_correlation,
    futures_market_correlation,
    serial_correlation,
    sterling_ratio,
    burke_ratio,
    kappa_three_ratio,
    adjusted_sharpe_ratio,
    stutzer_index,
    annual_alpha,
    annual_beta,
    residual_risk,
    conditional_sharpe_ratio,
    var_excess_return,
    regression_annual_return,
    r_cubed,
    annualized_cumulative_return,
    annual_active_return_by_year,
    treynor_mazuy_timing,
    henriksson_merton_timing,
    market_timing_return,
    alpha_percentile_rank,
    cornell_timing,
)

from fincore.constants import (
    DAILY,
    WEEKLY,
    MONTHLY,
    QUARTERLY,
    YEARLY,
)


from .perf_attrib import (
    perf_attrib,
    compute_exposures,
)
