"""Enhanced factor-analysis contracts and standalone Task 3 data kernel."""

from __future__ import annotations

from fincore.contracts.factor_analysis import FactorFunctionSpec
from fincore.contracts.factor_workflows import FactorWorkflowSpec
from fincore.factor_analysis.analysis import analyze_factor
from fincore.factor_analysis.calendar import (
    add_custom_calendar_timedelta,
    backshift_returns_series,
    diff_custom_calendar_timedeltas,
    get_forward_returns_columns,
    infer_trading_calendar,
    timedelta_strings_to_integers,
    timedelta_to_string,
)
from fincore.factor_analysis.costs import (
    FactorCapacityResult,
    FactorCostModel,
    FactorCostResult,
    apply_factor_costs,
    estimate_factor_capacity,
)
from fincore.factor_analysis.data import (
    FactorLossReport,
    MultiHorizonPreparedFactorData,
    PreparedFactorData,
    compute_forward_returns,
    prepare_factor_data,
    prepare_factor_data_by_horizon,
    prepare_factor_data_from_forward_returns,
    prepare_pit_factor_data,
    quantize_factor,
)
from fincore.factor_analysis.exceptions import (
    EnhancedNonMatchingTimezoneError,
    FactorDataError,
    FactorLossExceededError,
    MaxLossExceededError,
    NonMatchingTimezoneError,
)
from fincore.factor_analysis.inference import (
    ICInferenceResult,
    factor_model_inference,
)
from fincore.factor_analysis.models import (
    EventAnalysisModel,
    FactorAnalysisConfig,
    FactorAnalysisModel,
    FactorGroupAnalysis,
)
from fincore.factor_analysis.performance import (
    average_cumulative_return_by_quantile,
    common_start_returns,
    compute_mean_returns_spread,
    cumulative_returns,
    factor_alpha_beta,
    factor_information_coefficient,
    factor_rank_autocorrelation,
    factor_returns,
    factor_weights,
    mean_information_coefficient,
    mean_return_by_quantile,
    quantile_turnover,
)
from fincore.factor_analysis.pit import PITPoint, materialize_pit_factor, validate_pit_alignment
from fincore.factor_analysis.portfolio import (
    PyfolioFactorInputs,
    create_pyfolio_input,
    factor_cumulative_returns,
    factor_positions,
    positions,
)
from fincore.factor_analysis.tears import (
    FactorTearSheetArtifacts,
    GridFigure,
    close_owned_figures,
    create_event_returns_tear_sheet,
    create_event_study_tear_sheet,
    create_full_tear_sheet,
    create_information_tear_sheet,
    create_returns_tear_sheet,
    create_summary_tear_sheet,
    create_turnover_tear_sheet,
    show_owned_figures,
)

__all__ = [
    "EnhancedNonMatchingTimezoneError",
    "EventAnalysisModel",
    "FactorAnalysisConfig",
    "FactorAnalysisModel",
    "FactorCapacityResult",
    "FactorCostModel",
    "FactorCostResult",
    "FactorDataError",
    "FactorFunctionSpec",
    "FactorGroupAnalysis",
    "FactorLossExceededError",
    "FactorLossReport",
    "FactorTearSheetArtifacts",
    "FactorWorkflowSpec",
    "GridFigure",
    "ICInferenceResult",
    "MaxLossExceededError",
    "MultiHorizonPreparedFactorData",
    "NonMatchingTimezoneError",
    "PITPoint",
    "PreparedFactorData",
    "PyfolioFactorInputs",
    "add_custom_calendar_timedelta",
    "analyze_factor",
    "apply_factor_costs",
    "average_cumulative_return_by_quantile",
    "backshift_returns_series",
    "close_owned_figures",
    "common_start_returns",
    "compute_forward_returns",
    "compute_mean_returns_spread",
    "create_event_returns_tear_sheet",
    "create_event_study_tear_sheet",
    "create_full_tear_sheet",
    "create_information_tear_sheet",
    "create_pyfolio_input",
    "create_returns_tear_sheet",
    "create_summary_tear_sheet",
    "create_turnover_tear_sheet",
    "cumulative_returns",
    "diff_custom_calendar_timedeltas",
    "estimate_factor_capacity",
    "factor_alpha_beta",
    "factor_cumulative_returns",
    "factor_information_coefficient",
    "factor_model_inference",
    "factor_positions",
    "factor_rank_autocorrelation",
    "factor_returns",
    "factor_weights",
    "get_forward_returns_columns",
    "infer_trading_calendar",
    "materialize_pit_factor",
    "mean_information_coefficient",
    "mean_return_by_quantile",
    "positions",
    "prepare_factor_data",
    "prepare_factor_data_by_horizon",
    "prepare_factor_data_from_forward_returns",
    "prepare_pit_factor_data",
    "quantile_turnover",
    "quantize_factor",
    "show_owned_figures",
    "timedelta_strings_to_integers",
    "timedelta_to_string",
    "validate_pit_alignment",
]
