"""Explicit canonical operation declarations for the metrics domain."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from fincore.runtime.specs import OperationSpec, make_operations_provider

if TYPE_CHECKING:
    from collections.abc import Callable

from .alpha_beta import (
    alpha,
    alpha_aligned,
    alpha_beta,
    alpha_beta_aligned,
    alpha_percentile_rank,
    annual_alpha,
    annual_beta,
    beta,
    beta_aligned,
    down_alpha_beta,
    up_alpha_beta,
)
from .consecutive import (
    consecutive_stats,
    max_consecutive_down_days,
    max_consecutive_down_end_date,
    max_consecutive_down_months,
    max_consecutive_down_start_date,
    max_consecutive_down_weeks,
    max_consecutive_gain,
    max_consecutive_loss,
    max_consecutive_up_days,
    max_consecutive_up_end_date,
    max_consecutive_up_months,
    max_consecutive_up_start_date,
    max_consecutive_up_weeks,
    max_single_day_gain,
    max_single_day_gain_date,
    max_single_day_loss,
    max_single_day_loss_date,
)
from .drawdown import (
    gen_drawdown_table,
    get_all_drawdowns,
    get_all_drawdowns_detailed,
    get_max_drawdown,
    get_max_drawdown_period,
    get_max_drawdown_underwater,
    get_top_drawdowns,
    max_drawdown,
    max_drawdown_days,
    max_drawdown_months,
    max_drawdown_recovery_days,
    max_drawdown_recovery_months,
    max_drawdown_recovery_weeks,
    max_drawdown_weeks,
    second_max_drawdown,
    second_max_drawdown_days,
    second_max_drawdown_recovery_days,
    third_max_drawdown,
    third_max_drawdown_days,
    third_max_drawdown_recovery_days,
)
from .ratios import (
    adjusted_sharpe_ratio,
    burke_ratio,
    cal_treynor_ratio,
    calmar_ratio,
    capture,
    common_sense_ratio,
    conditional_sharpe_ratio,
    down_capture,
    down_capture_return,
    excess_sharpe,
    information_ratio,
    kappa_three_ratio,
    m_squared,
    mar_ratio,
    omega_ratio,
    sharpe_ratio,
    sortino_ratio,
    stability_of_timeseries,
    sterling_ratio,
    treynor_ratio,
    up_capture,
    up_capture_return,
    up_down_capture,
)
from .returns import aggregate_returns, cum_returns, cum_returns_final, simple_returns
from .returns import normalize as normalize_returns
from .risk import (
    annual_volatility,
    beta_fragility_heuristic,
    beta_fragility_heuristic_aligned,
    conditional_value_at_risk,
    downside_risk,
    residual_risk,
    tail_ratio,
    tracking_error,
    value_at_risk,
    var_excess_return,
)
from .rolling import (
    roll_alpha,
    roll_alpha_aligned,
    roll_alpha_beta,
    roll_alpha_beta_aligned,
    roll_annual_volatility,
    roll_beta,
    roll_beta_aligned,
    roll_down_capture,
    roll_max_drawdown,
    roll_sharpe_ratio,
    roll_sortino_ratio,
    roll_up_capture,
    roll_up_down_capture,
    rolling_beta,
    rolling_regression,
    rolling_sharpe,
    rolling_volatility,
)
from .stats import (
    bond_market_correlation,
    capm_r_squared,
    futures_market_correlation,
    hurst_exponent,
    kurtosis,
    loss_rate,
    r_cubed,
    r_cubed_turtle,
    relative_win_rate,
    serial_correlation,
    skewness,
    stock_market_correlation,
    stutzer_index,
    tracking_difference,
    win_rate,
)
from .timing import (
    cornell_timing,
    extract_interesting_date_ranges,
    henriksson_merton_timing,
    market_timing_return,
    treynor_mazuy_timing,
)
from .yearly import (
    annual_active_return,
    annual_active_return_by_year,
    annual_return,
    annual_return_by_year,
    annual_volatility_by_year,
    information_ratio_by_year,
    max_drawdown_by_year,
    sharpe_ratio_by_year,
)

__all__ = ["operations"]

_BINDINGS: tuple[tuple[str, Callable[..., Any]], ...] = (
    ("metrics.alpha_beta.alpha", alpha),
    ("metrics.alpha_beta.alpha_aligned", alpha_aligned),
    ("metrics.alpha_beta.alpha_beta", alpha_beta),
    ("metrics.alpha_beta.alpha_beta_aligned", alpha_beta_aligned),
    ("metrics.alpha_beta.alpha_percentile_rank", alpha_percentile_rank),
    ("metrics.alpha_beta.annual_alpha", annual_alpha),
    ("metrics.alpha_beta.annual_beta", annual_beta),
    ("metrics.alpha_beta.beta", beta),
    ("metrics.alpha_beta.beta_aligned", beta_aligned),
    ("metrics.alpha_beta.down_alpha_beta", down_alpha_beta),
    ("metrics.alpha_beta.up_alpha_beta", up_alpha_beta),
    ("metrics.consecutive.consecutive_stats", consecutive_stats),
    ("metrics.consecutive.max_consecutive_down_days", max_consecutive_down_days),
    ("metrics.consecutive.max_consecutive_down_end_date", max_consecutive_down_end_date),
    ("metrics.consecutive.max_consecutive_down_months", max_consecutive_down_months),
    ("metrics.consecutive.max_consecutive_down_start_date", max_consecutive_down_start_date),
    ("metrics.consecutive.max_consecutive_down_weeks", max_consecutive_down_weeks),
    ("metrics.consecutive.max_consecutive_gain", max_consecutive_gain),
    ("metrics.consecutive.max_consecutive_loss", max_consecutive_loss),
    ("metrics.consecutive.max_consecutive_up_days", max_consecutive_up_days),
    ("metrics.consecutive.max_consecutive_up_end_date", max_consecutive_up_end_date),
    ("metrics.consecutive.max_consecutive_up_months", max_consecutive_up_months),
    ("metrics.consecutive.max_consecutive_up_start_date", max_consecutive_up_start_date),
    ("metrics.consecutive.max_consecutive_up_weeks", max_consecutive_up_weeks),
    ("metrics.consecutive.max_single_day_gain", max_single_day_gain),
    ("metrics.consecutive.max_single_day_gain_date", max_single_day_gain_date),
    ("metrics.consecutive.max_single_day_loss", max_single_day_loss),
    ("metrics.consecutive.max_single_day_loss_date", max_single_day_loss_date),
    ("metrics.drawdown.gen_drawdown_table", gen_drawdown_table),
    ("metrics.drawdown.get_all_drawdowns", get_all_drawdowns),
    ("metrics.drawdown.get_all_drawdowns_detailed", get_all_drawdowns_detailed),
    ("metrics.drawdown.get_max_drawdown", get_max_drawdown),
    ("metrics.drawdown.get_max_drawdown_period", get_max_drawdown_period),
    ("metrics.drawdown.get_max_drawdown_underwater", get_max_drawdown_underwater),
    ("metrics.drawdown.get_top_drawdowns", get_top_drawdowns),
    ("metrics.drawdown.max_drawdown", max_drawdown),
    ("metrics.drawdown.max_drawdown_days", max_drawdown_days),
    ("metrics.drawdown.max_drawdown_months", max_drawdown_months),
    ("metrics.drawdown.max_drawdown_recovery_days", max_drawdown_recovery_days),
    ("metrics.drawdown.max_drawdown_recovery_months", max_drawdown_recovery_months),
    ("metrics.drawdown.max_drawdown_recovery_weeks", max_drawdown_recovery_weeks),
    ("metrics.drawdown.max_drawdown_weeks", max_drawdown_weeks),
    ("metrics.drawdown.second_max_drawdown", second_max_drawdown),
    ("metrics.drawdown.second_max_drawdown_days", second_max_drawdown_days),
    ("metrics.drawdown.second_max_drawdown_recovery_days", second_max_drawdown_recovery_days),
    ("metrics.drawdown.third_max_drawdown", third_max_drawdown),
    ("metrics.drawdown.third_max_drawdown_days", third_max_drawdown_days),
    ("metrics.drawdown.third_max_drawdown_recovery_days", third_max_drawdown_recovery_days),
    ("metrics.ratios.adjusted_sharpe_ratio", adjusted_sharpe_ratio),
    ("metrics.ratios.burke_ratio", burke_ratio),
    ("metrics.ratios.cal_treynor_ratio", cal_treynor_ratio),
    ("metrics.ratios.calmar_ratio", calmar_ratio),
    ("metrics.ratios.capture", capture),
    ("metrics.ratios.common_sense_ratio", common_sense_ratio),
    ("metrics.ratios.conditional_sharpe_ratio", conditional_sharpe_ratio),
    ("metrics.ratios.down_capture", down_capture),
    ("metrics.ratios.down_capture_return", down_capture_return),
    ("metrics.ratios.excess_sharpe", excess_sharpe),
    ("metrics.ratios.information_ratio", information_ratio),
    ("metrics.ratios.kappa_three_ratio", kappa_three_ratio),
    ("metrics.ratios.m_squared", m_squared),
    ("metrics.ratios.mar_ratio", mar_ratio),
    ("metrics.ratios.omega_ratio", omega_ratio),
    ("metrics.ratios.sharpe_ratio", sharpe_ratio),
    ("metrics.ratios.sortino_ratio", sortino_ratio),
    ("metrics.ratios.stability_of_timeseries", stability_of_timeseries),
    ("metrics.ratios.sterling_ratio", sterling_ratio),
    ("metrics.ratios.treynor_ratio", treynor_ratio),
    ("metrics.ratios.up_capture", up_capture),
    ("metrics.ratios.up_capture_return", up_capture_return),
    ("metrics.ratios.up_down_capture", up_down_capture),
    ("metrics.returns.aggregate_returns", aggregate_returns),
    ("metrics.returns.cum_returns", cum_returns),
    ("metrics.returns.cum_returns_final", cum_returns_final),
    ("metrics.returns.normalize", normalize_returns),
    ("metrics.returns.simple_returns", simple_returns),
    ("metrics.risk.annual_volatility", annual_volatility),
    ("metrics.risk.beta_fragility_heuristic", beta_fragility_heuristic),
    ("metrics.risk.beta_fragility_heuristic_aligned", beta_fragility_heuristic_aligned),
    ("metrics.risk.conditional_value_at_risk", conditional_value_at_risk),
    ("metrics.risk.downside_risk", downside_risk),
    ("metrics.risk.residual_risk", residual_risk),
    ("metrics.risk.tail_ratio", tail_ratio),
    ("metrics.risk.tracking_error", tracking_error),
    ("metrics.risk.value_at_risk", value_at_risk),
    ("metrics.risk.var_excess_return", var_excess_return),
    ("metrics.rolling.roll_alpha", roll_alpha),
    ("metrics.rolling.roll_alpha_aligned", roll_alpha_aligned),
    ("metrics.rolling.roll_alpha_beta", roll_alpha_beta),
    ("metrics.rolling.roll_alpha_beta_aligned", roll_alpha_beta_aligned),
    ("metrics.rolling.roll_annual_volatility", roll_annual_volatility),
    ("metrics.rolling.roll_beta", roll_beta),
    ("metrics.rolling.roll_beta_aligned", roll_beta_aligned),
    ("metrics.rolling.roll_down_capture", roll_down_capture),
    ("metrics.rolling.roll_max_drawdown", roll_max_drawdown),
    ("metrics.rolling.roll_sharpe_ratio", roll_sharpe_ratio),
    ("metrics.rolling.roll_sortino_ratio", roll_sortino_ratio),
    ("metrics.rolling.roll_up_capture", roll_up_capture),
    ("metrics.rolling.roll_up_down_capture", roll_up_down_capture),
    ("metrics.rolling.rolling_beta", rolling_beta),
    ("metrics.rolling.rolling_regression", rolling_regression),
    ("metrics.rolling.rolling_sharpe", rolling_sharpe),
    ("metrics.rolling.rolling_volatility", rolling_volatility),
    ("metrics.stats.bond_market_correlation", bond_market_correlation),
    ("metrics.stats.capm_r_squared", capm_r_squared),
    ("metrics.stats.futures_market_correlation", futures_market_correlation),
    ("metrics.stats.hurst_exponent", hurst_exponent),
    ("metrics.stats.kurtosis", kurtosis),
    ("metrics.stats.loss_rate", loss_rate),
    ("metrics.stats.r_cubed", r_cubed),
    ("metrics.stats.r_cubed_turtle", r_cubed_turtle),
    ("metrics.stats.relative_win_rate", relative_win_rate),
    ("metrics.stats.serial_correlation", serial_correlation),
    ("metrics.stats.skewness", skewness),
    ("metrics.stats.stock_market_correlation", stock_market_correlation),
    ("metrics.stats.stutzer_index", stutzer_index),
    ("metrics.stats.tracking_difference", tracking_difference),
    ("metrics.stats.win_rate", win_rate),
    ("metrics.timing.cornell_timing", cornell_timing),
    ("metrics.timing.extract_interesting_date_ranges", extract_interesting_date_ranges),
    ("metrics.timing.henriksson_merton_timing", henriksson_merton_timing),
    ("metrics.timing.market_timing_return", market_timing_return),
    ("metrics.timing.treynor_mazuy_timing", treynor_mazuy_timing),
    ("metrics.yearly.annual_active_return", annual_active_return),
    ("metrics.yearly.annual_active_return_by_year", annual_active_return_by_year),
    ("metrics.yearly.annual_return", annual_return),
    ("metrics.yearly.annual_return_by_year", annual_return_by_year),
    ("metrics.yearly.annual_volatility_by_year", annual_volatility_by_year),
    ("metrics.yearly.information_ratio_by_year", information_ratio_by_year),
    ("metrics.yearly.max_drawdown_by_year", max_drawdown_by_year),
    ("metrics.yearly.sharpe_ratio_by_year", sharpe_ratio_by_year),
)
_OPERATIONS = tuple(
    OperationSpec(
        operation_id=operation_id,
        capability_id=operation_id,
        domain="metrics",
        callable=callable_,
        provenance={"owner": "metrics", "kernel_module": callable_.__module__},
    )
    for operation_id, callable_ in _BINDINGS
)


operations = make_operations_provider(_OPERATIONS)
